---
apiVersion: v1
kind: Service
metadata:
  name: node-node-port
spec:
  selector:
    app: node-deployment
  ports:
    - port: 8080
      targetPort: 3000
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  server_port: 3000
  database_username: test11
  database_password: qwerty11
  database_hostname: postgres-service



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: node-deployment
      labels:
        app: node-deployment
    spec:
      containers:
      - name: node-deployment
        image: node:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: node-deployment
