---
apiVersion: v1
kind: Service
metadata:
  name: node-node-port
spec:
  selector:
    app: node-deployment
  ports:
    - port: 8080
      targetPort: 3000
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  server_port: 3000
  PORT: 3000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: node-deployment
      labels:
        app: node-deployment
    spec:
      containers:
      - name: node-deployment
        image: godhasu1/node_test113
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-config
          - configMapRef:
              name: postgres-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: node-deployment
