apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-service
  ports:
    - port: 8080
      targetPort: 5432
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  serviceName: postgres-ep
  replicas: 1
  template:
    metadata:
      name: postgres-db
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432

      restartPolicy: Always
  selector:
    matchLabels:
      app: postgres-db
