apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-service
  ports:
    - port: 8080
      targetPort: 5432
  type: NodePort

---
##spostare su secret successivamente
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DATABASE_USERNAME: test11
  DATABASE_PASSWORD: qwerty11
  DATABASE_HOST: postgres-service
  DATABASE_NAME: superapp
  DATABASE_PORT: 5432
  POSTGRES_USER: test11
  POSTGRES_PASSWORD: qwerty11
  POSTGRES_DB: superapp

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  serviceName: postgres-ep
  replicas: 1
  template:
    metadata:
      name: postgres-db
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432

      restartPolicy: Always
  selector:
    matchLabels:
      app: postgres-db
